name: DeathCounter
main: net.krinsoft.deathcounter.DeathCounter
version: ${project.version}-b${project.build.number}
author: krinsdeath
load: startup

commands:
  deathcounter:
    description: Main command for DeathCounter
    usage: /<command> [options]...
    aliases: [dc]
  stats:
    description: Show the statistics for the command sender or his specified target
    usage: /<command> [target] [-aomp]
  leaders:
    description: Show the leaderboards for the specified monster
    usage: /<command> [monster]
  contract:
    description: Draw up a contract for a player bounty
    usage: /<command> [options]...