name: KillSuite
main: net.krinsoft.killsuite.KillSuite
version: maven-version-number
author: krinsdeath
load: startup

commands:
  killsuite:
    description: Main command for KillSuite
    usage: /<command> [options]...
    aliases: [ks]
  stats:
    description: Show the statistics for the command sender or his specified target
    usage: /<command> [target] [-aomp]
  leaders:
    description: Show the leaderboards for the specified monster
    usage: /<command> [monster]
  contract:
    description: Draw up a contract for a player bounty
    usage: /<command> [options]...